version: "3"

services:
  fastapi:
    build: backend/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: backend
    volumes:
      - lib-volume:/var/lib/assets

  streamlit:
    build: frontend/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: frontend
    volumes:
      - lib-volume:/var/lib/assets

volumes:
  lib-volume:

networks:
  deploy_network:
    driver: bridge
